steps:
  # Build frontend
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd master-agent-frontend
        npm install
        npm run build
        
  # Deploy frontend service
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'app'
      - 'deploy'
      - 'master-agent-frontend/app.yaml'
      - '--quiet'
        
  # Deploy backend service
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'app'
      - 'deploy'
      - 'master-agent-backend/app.yaml'
      - '--quiet'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
