steps:
  # Backend build and deployment
  - name: "gcr.io/cloud-builders/docker"
    args: [ "build", "-t", "gcr.io/$PROJECT_ID/master-agent-backend", "./master-agent-backend" ]

  - name: "gcr.io/cloud-builders/docker"
    args: [ "push", "gcr.io/$PROJECT_ID/master-agent-backend" ]

  # Frontend build
  - name: "node:18"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        cd master-agent-frontend
        npm install
        npm run build

  # Deploy frontend to GCS bucket
  - name: "gcr.io/cloud-builders/gsutil"
    args: [ "cp", "-r", "master-agent-frontend/dist/*", "gs://$PROJECT_ID-frontend/" ]

images:
  - "gcr.io/$PROJECT_ID/master-agent-backend"