steps:
  # Deploy Backend Only
  - name: 'gcr.io/cloud-builders/gcloud'
    dir: 'master-agent-backend'
    args: ['app', 'deploy', 'app.yaml', '--quiet', '--project=pure-album-439502-s4']

logsBucket: 'gs://master-agent-build-logs-dev'
options:
  logging: GCS_ONLY
timeout: '600s'