runtime: python39
service: backend-prod

env_variables:
  FLASK_ENV: production

automatic_scaling:
  min_instances: 0
  max_instances: 10

resources:
  cpu: 1
  memory_gb: 0.5

entrypoint: gunicorn -b :$PORT main:app
